# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "bf99e755a15b78cc0dc496d45f1cd75e"
name = "Ello VTO Public"
application_url = "https://ello-vto-public-13593516897.us-central1.run.app"
embedded = true

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "unauthenticated_read_product_listings,unauthenticated_read_product_tags"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://ello-vto-public-13593516897.us-central1.run.app/auth/callback"
]

[webhooks.privacy_compliance]
customer_data_request_url = "https://ello-vto-public-13593516897.us-central1.run.app/webhooks/privacy"
customer_redaction_url = "https://ello-vto-public-13593516897.us-central1.run.app/webhooks/privacy"
shop_redaction_url = "https://ello-vto-public-13593516897.us-central1.run.app/webhooks/privacy"
