# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5a061b1380e2f426010459c372872b55"
name = "Ello Storefront App"
application_url = "https://ello-shopify-app-u5htiuxfrq-uc.a.run.app"
embedded = true

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "unauthenticated_read_product_listings,unauthenticated_read_product_tags"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://ello-shopify-app-u5htiuxfrq-uc.a.run.app/auth/callback"
]

[build]
automatically_update_urls_on_dev = true
